Home page improvement
gaurav613/fydp_bess pull request #25
Opened 2022-02-24 15:26 UTC by Kyle199910

Minor adjustment to the home page: text adjustment and lighter shape

2022-02-27 01:25 UTC, gaurav613 commented
This looks good to me. @Rolo123y can you do some testing to make sure everything works well?

2022-02-27 02:48 UTC, Rolo123y requested changes
Can you remove the app/__pycache__ stuff from the commits?

2022-02-27 21:04 UTC, Rolo123y requested changes

2022-02-27 21:04 UTC, Rolo123y commented on app/templates/FAQ.html
>  {% extends 'base.html'%} {% block title%} FAQ {% endblock%} {% block styles %}
{% block styles %} shouldnt be defined here as it is defined a bit under too.

2022-02-27 21:04 UTC, Rolo123y commented on app/templates/FAQ.html
>  <body>
replace this <body> tag with {% block content %}

2022-02-27 21:04 UTC, Rolo123y commented on app/templates/FAQ.html
>  </html>
remove these tags.

2022-02-28 00:35 UTC, Rolo123y approved these changes
We can resolve the __init__.py changes

other than that everything looks good!

2022-02-28 00:37 UTC, gaurav613 commented
Changes look good - I have resolved the conflicts. Merging now.

2022-02-28 00:37 UTC, merged