Uploading initial opt model.py file
gaurav613/fydp_bess pull request #28
Opened 2022-03-01 22:06 UTC by AaronDzf

Model still WIP - only use it as sample.
Create pipeline functions using a helper.py file

2022-03-01 23:20 UTC, gaurav613 reviewed
can you mark the variables that will be assigned to the inputs? it can be done in the PR itself

2022-03-11 07:10 UTC, Rolo123y requested changes

2022-03-11 07:10 UTC, Rolo123y commented on app/routes.py
> +    result = optimize()
need to pass in the dictionary called 'completed_form' into optimize()

2022-03-11 07:10 UTC, Rolo123y commented on app/optimization_model.py
> +def optimize(CN = 0.17, CM = 0.113, CF = 0.082, UN_m = 500, UM_m = 300, UF_m = 380):
need to parse the incoming dictionary and assign correct variables for the model.

2022-03-11 07:12 UTC, Rolo123y commented on app/optimization_model.py
> +def optimize(CN = 0.17, CM = 0.113, CF = 0.082, UN_m = 500, UM_m = 300, UF_m = 380):
**time of use** dictionary will look as follows:
<img width="143" alt="image" src="https://user-images.githubusercontent.com/52054023/157819706-e7fe14dc-e236-4b63-8c4a-148951af61ee.png">

**Tiered** dictionary will look as follows:
<img width="139" alt="image" src="https://user-images.githubusercontent.com/52054023/157819780-e808b907-90df-4f82-a181-b412ce1d9bea.png">

2022-03-16 20:38 UTC, gaurav613 commented
Looks good to me, merging now. Change can be made later.

2022-03-16 20:38 UTC, Rolo123y approved these changes

2022-03-16 20:38 UTC, merged